// const shaderMaps = new THREE.ShaderMaterial({
//   uniforms: {
//     time: { value: 0 },
//     resolution: { value: new THREE.Vector2() },
//     mouse: { value: new THREE.Vector2() },
//     date: { value: new THREE.Vector2() },
//     frameCount: { value: 0 },
//     cameraPosition: { value: new THREE.Vector3() },
//     cameraRotation: { value: new THREE.Vector3() },
//     cameraDirection: { value: new THREE.Vector3() },
//     cameraNear: { value: 0.1 },
//     cameraFar: { value: 1000 },
//     cameraFOV: { value: 75 },
//     cameraAspect: { value: 1 },
//     cameraZoom: { value: 1 },
//     cameraFocus: { value: 0 },
//     cameraTarget: { value: new THREE.Vector3() },
//     cameraViewport: { value: new THREE.Vector4() },
//     cameraResolution: { value: new THREE.Vector2() },
//     cameraFocalLength: { value: 0.01 },
//     cameraFilmGauge: { value: 0.98 },
//     cameraFilmOffset: { value: 0.02 },
//     cameraFilmWidth: { value: 0.02 },
//     cameraFilmHeight: { value: 0.02 },
//     cameraFilmSpeed: { value: 0},
//     cameraFilmNoise: { value: 0},
//     cameraFilmGrain: { value: 0},
//     cameraFilmGrainSize: { value: 0},
//     cameraFilmGrainRandom: { value: 0},
//     cameraFilmExposure: { value: 0},
//     cameraFilmExposureMax: { value: 0},
//     cameraFilmExposureMin: { value: 0},
//     cameraFilmContrast: { value: 0},
//     cameraFilmContrastMax: { value: 0},
//     cameraFilmContrastMin: { value: 0},
//     cameraFilmExposure: { value: 0},
//     cameraFilmExposureBias: { value: 0},
//     cameraFilmBlur: { value: 0},
//     cameraFilmBlurAmount: { value: 0},
//     cameraFilmBlurRadius: { value: 0},
//     cameraFilmBlurSTD: { value: 0},
//     cameraFilmBlurIntensity: { value: 0},
//     cameraFilmBlurDepth: { value: 0},
//     cameraFilmBlurChroma: { value: 0},
//     cameraFilmBlurChromaAmount: { value: 0},
//     cameraFilmBlurChromaRadius: { value: 0},
//     cameraFilmBlurChromaSTD: { value: 0},
//     cameraFilmBlurChromaIntensity: { value: 0},
//     cameraFilmBlurChromaDepth: { value: 0},
//     cameraFilmBlurChromaThreshold: { value: 0},
//     cameraFilmBlurChroma: { value: 0}
//     },
//     // vertexShader: document.getElementById("vertexshader").textContent,
//     // fragmentShader: document.getElementById("fragmentshader").textContent,
//     side: THREE.DoubleSide,
//     fog: true,
//     lights: true,
//     precision: "highp",
//     flatShading: false,
//     wireframe: false,
//     wireframeLinewidth: 1,
//     vertexColors: false,
//     skinning: false,
//     morphTargets: false,
//     morphNormals: false,
//     fog: false,
//     shading: THREE.SmoothShading,
//     vertexTangents: false,
//     map: textureGenerator.g_texture(textureGenerator.wildCard, 4),
//     alphaMap: textureGenerator.g_texture(textureGenerator.wildCard, 4),
//     specularMap: textureGenerator.g_texture(textureGenerator.wildCard, 4),
//     aoMap: textureGenerator.g_texture(textureGenerator.wildCard, 4)
// })
//------------------------------------------------------------------------------ ◉
